language: node_js
node_js:
- '0.10'
before_install:
- npm install -g grunt-cli
deploy:
  provider: npm
  email: ajroyle@gmail.com
  api_key:
    secure: H+jNkO457vNczlKu+CowLHU9WpZv4jo0V/PoqDQFA0Tz2Z9p6m+Fw1jRxVR/YBKnQaih3waoHqzCbIwLn5rd+SqOQ/2ccyxoKGJJaLqYbLwXHcO175S8EyXDPmpPUsaSse1EpY195mtwRKd6XLEFH48NAQZdD8NtFBsFwL3tJL0=
  on:
    all_branches: true
    tags: true
    repo: opentable/hapi-hobknob-client
